name 'ceritsc-cerit'
version '0.0.1'
source 'git@github.com:CERIT-SC/puppet-cerit.git'
author 'ceritsc'
license 'WTFPL'
summary 'Puppet module for various automation tasks in CERIT-SC'
description 'Module for CERIT-SC'
project_page 'https://github.com/CERIT-SC/puppet-cerit'

## Add dependencies, if any:
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/concat', '>= 1.1.0'
dependency 'puppetlabs/firewall', '>= 1.0.0'
dependency 'puppetlabs/apt', '>= 1.4.1'
dependency 'domcleal/augeasproviders', '>= 1.0.2'
dependency 'adrien/network', '>= 0.4.1'
